name: setup
inputs:
  cwd:
    required: false
    default: "${PWD}"
description: "Setup Machine Action"
runs:
  using: composite
  steps:
    - name: Set environment variables
      run: |-
        touch $BASH_ENV
        if [[ "${CIRCLE_BRANCH}" == "develop" ]]; then echo 'export DEVELOP=true' >> $BASH_ENV; fi
        if [[ "${CIRCLE_BRANCH}" =~ ^release- ]]; then echo 'export RELEASE=true' >> $BASH_ENV; fi
        source $BASH_ENV
      shell: bash
    - name: Install Dependencies
      run: |-
        # Install system dependencies
        sudo apt-get update
        sudo apt-get install python-dev python-pip time
        sudo pip install -U pip setuptools
        sudo pip install awscli==1.18.85 datadog==0.40.1

        # Install node dependencies
        node ./scripts/gtime.js monorepo_install npm ci

        # Build the PWA
        npm run lerna -- run analyze-build --scope "retail-react-app"

        # Report bundle sizes
        node ./scripts/report-bundle-size.js
    
        # Check that packages are all using the same versions of compilers, etc.
        node ./scripts/check-dependencies.js

        # Install Lighthouse CI CLI
        sudo npm install -g @lhci/cli
      shell: bash
