name: create_mrt_credentials_file
runs:
  using: composit
  env:
    MOBIFY_CLIENT_USER: ${{ secrets.MOBIFY_CLIENT_USER }}
    MOBIFY_CLIENT_API_KEY: ${{ secrets.MOBIFY_CLIENT_API_KEY }}

  steps:
  - name: Create MRT credentials file
    run: |-
      # Add credentials file at ~/.mobify so we can upload to Mobify Cloud
      npm run save-credentials --prefix packages/template-retail-react-app -- --user "$MOBIFY_CLIENT_USER" --key "$MOBIFY_CLIENT_API_KEY"
    shell: bash

