name: snyk
runs:
  using: composite
  steps:
    # TODO: update SNYK_TOKEN in secrets
    # - name: Audit Generated Project
    #   run: |-
    #       if [[ "${{ github.ref }}" == "develop" ]]; then
    #           # Run snyk auth - authenticate snyk using environment variables to add the token
    #           snyk auth $SNYK_TOKEN

    #           snyk monitor --ignore-policy --remote-repo-url='https://github.com/SalesforceCommerceCloud/pwa-kit.git' --project-name='generated-scaffold-pwa'
    #       fi
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}