name: publish_to_npm
input:
  NODE_AUTH_TOKEN:
    description: "Node auth token"
runs:
  using: composite
  steps:
  - name: Publish to NPM
    run: |-
      # Add NPM token to allow publishing
      echo "//registry.npmjs.org/:_authToken=${{ inputs.NODE_AUTH_TOKEN }}" > ~/.npmrc

      if [[ $RELEASE ]]; then
        # Publish all changed packages. The "from-package" arg means "look
        # at the version numbers in each package.json file and if that doesn't
        # exist on NPM, publish"
        npm run lerna -- publish from-package --yes --no-verify-access --dry-run
      fi

      # Cleanup
      rm ~/.npmrc
    shell: bash