name: SalesforceCommerceCloud/pwa-kit/test
on:
  push:
    branches:
    - github-actions
jobs:
  testNode14:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.x
          cache: npm

      - uses: "./.github/actions/runtests"

