name: SalesforceCommerceCloud/pwa-kit/test
on:
  push:
    branches:
    - github-actions
jobs:
  test_matrix:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        node: [ 14 ]
        include:
          - os: ubuntu-latest
            node: 14
            npm: 7
          - os: ubuntu-latest
            node: 14
            npm: 8
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Setup Machine Ubuntu
        if: matrix.npm == 'ubuntu-latest'
        uses: "./.github/actions/setup-ubuntu"

      - name: Setup Machine Windows
        if: matrix.npm == 'windows-latest'
        uses: "./.github/actions/setup-windows"

      - name: NPM version
        if: ${{ matrix.npm }}
        run: npm install -g npm@${{ matrix.npm }}
      - run: npm --version

      - name: Run tests
        uses: "./.github/actions/runtests"


