name: SalesforceCommerceCloud/pwa-kit/test
on:
  schedule:
    - cron: 0 8 * * *
  push:
     branches:
     # TODO: Before merging remove branches filter
     - github-actions
jobs:
  pwa-kit:
    strategy:
      fail-fast: false
      matrix:
        node: [14]
        npm: [6, 7, 8]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Save NPM version
        run: |-
            echo "NPM_VERSION=${{ matrix.npm }}" >> $GITHUB_ENV
        shell: bash

      - name: Setup Ubuntu Machine
        uses: "./.github/actions/setup_ubuntu"

      - name: Install node dependencies with NPM version
        if: matrix.npm != 6
        run: |- 
          npm install -g npm@${{ matrix.npm }}
          npm ci

      - name: NPM version
        run: npm --version

      - name: Run unit tests
        uses: "./.github/actions/unit_tests"

      - name: Run Lighthouse CI on the PWA
        if: matrix.npm == 6
        uses: "./.github/actions/lighthouse_ci"

      - name: Smoke test scripts
        if: matrix.npm == 6
        uses: "./.github/actions/smoke_tests"

      - name: Create MRT credentials file
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6
        uses: "./.github/actions/create_mrt"
        with:
          mobify_user: ${{ secrets.MOBIFY_CLIENT_USER }}
          mobify_api_key: ${{ secrets.MOBIFY_CLIENT_API_KEY }}

      - name: Push Bundle to MRT
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6 
        uses: "./.github/actions/push_to_mrt"
        with:
          DEVELOP: $DEVELOP
          RELEASE: $RELEASE

      #TODO: remove --dry-run from install command
      - name: Publish to NPM
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6
        uses: "./.github/actions/publish_to_npm"
        with:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Send GitHub Action data to Slack workflow (PWA Kit)
        id: slack
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && failure() && github.ref == 'refs/heads/develop' && matrix.npm == 6
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "test": "testNode${{ matrix.node }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  pwa-kit-windows:
    strategy:
        fail-fast: false
        matrix:
          node: [14]
          npm: [6]
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}
            cache: npm

        - name: Setup Windows Machine
          uses: "./.github/actions/setup_windows"

        - name: NPM version
          run: npm --version

        - name: Run tests
          uses: "./.github/actions/unit_tests"

  generated:
    strategy:
      fail-fast: false
      matrix:
        template: [test-project, retail-react-app-demo, express-minimal-test-project, typescript-minimal-test-project]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Setup Ubuntu Machine
        uses: "./.github/actions/setup_ubuntu"

      - name: Generate ${{ matrix.template }} project
        run: |-
          set GENERATOR_PRESET=${{ matrix.template }}
          node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir generated-${{ matrix.template }}
        env:
          GENERATOR_PRESET: ${{ matrix.template }}
        timeout-minutes: 5

      - name: Run tests
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/unit_tests"
        with:
          cwd: generated-${{ matrix.template }}

      - name: Smoke test scripts
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/smoke_tests"
        with:
          dir: generated-${{ matrix.template }}

      - name: Count Generated Project Dependencies
        id: count_deps
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/count_deps"

      - name: Store Verdaccio logfile artifact
        uses: actions/upload-artifact@v3
        with:
          path: packages/pwa-kit-create-app/local-npm-repo/verdaccio.log
      
      - name: Audit Generated Project
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
        uses: "./.github/actions/snyk"
        with:
          snyk_token: ${{ secrets.SNYK_TOKEN }}

      - name: Send metrics to Datadog
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
        uses: "./.github/actions/datadog"
        with:
          datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
          TOTAL_PACKAGES: $TOTAL_PACKAGES

      - name: Create MRT credentials file
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
        uses: "./.github/actions/create_mrt"
        with:
          mobify_user: ${{ secrets.MOBIFY_CLIENT_USER }}
          mobify_api_key: ${{ secrets.MOBIFY_CLIENT_API_KEY }}

      - name: Push Bundle to MRT
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
        uses: "./.github/actions/push_to_mrt"
        with:
          DEVELOP: $DEVELOP
          RELEASE: $RELEASE

      - name: Send GitHub Action data to Slack workflow (Generated)
        id: slack
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && failure() && github.ref == 'refs/heads/github-actions' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "test": "generated ${{ matrix.template }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  generated-windows:
    strategy:
      fail-fast: false
      matrix:
        template: [test-project, retail-react-app-demo, express-minimal-test-project, typescript-minimal-test-project]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Setup Windows Machine
        uses: "./.github/actions/setup_windows"

      - name: Generate ${{ matrix.template }} project
        run: |-
          set GENERATOR_PRESET=${{ matrix.template }}
          node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir generated-${{ matrix.template }}
        env:
          GENERATOR_PRESET: ${{ matrix.template }}
        timeout-minutes: 5

      - name: Run unit tests
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/unit_tests"
        with:
          cwd: generated-${{ matrix.template }}

      - name: Smoke test scripts
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/smoke_tests"
        with:
          dir: generated-${{ matrix.template }}

      - name: Count Generated Project Dependencies
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/countdeps"

      - name: Store Verdaccio logfile artifact
        uses: actions/upload-artifact@v3
        with:
          path: packages/pwa-kit-create-app/local-npm-repo/verdaccio.log


