name: SalesforceCommerceCloud/pwa-kit/test
on:
  schedule:
    - cron: 0 8 * * *
  push:
  #    branches:
  #    # TODO: Before merging remove branches filter
  #    - github-actions
jobs:
  pwa-kit:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [14]
        npm: [6, 7, 8]
        exclude:
          - os: windows-latest
            node: 14
            npm: 7
          - os: windows-latest
            node: 14
            npm: 8
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Save NPM version
        run: |-
            echo "NPM_VERSION=${{ matrix.npm }}" >> $GITHUB_ENV
        shell: bash

      - name: Setup Ubuntu Machine
        if: matrix.os == 'ubuntu-latest'
        uses: "./.github/actions/setup_ubuntu"

      - name: Setup Windows Machine
        if: matrix.os == 'windows-latest'
        uses: "./.github/actions/setup_windows"

      - name: Install node dependencies with NPM version
        if: matrix.npm != 6
        run: |- 
          npm install -g npm@${{ matrix.npm }}
          npm ci

      - name: NPM version
        run: npm --version

      - name: Run tests
        uses: "./.github/actions/runtests"

      - name: Run Lighthouse CI on the PWA
        if: matrix.os == 'ubuntu-latest' && matrix.npm == 6
        uses: "./.github/actions/lighthouse-ci"

      - name: Smoke test scripts
        if: matrix.os == 'ubuntu-latest' && matrix.npm == 6
        uses: "./.github/actions/smoketestscripts"

      - name: Create MRT credentials file
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6 && matrix.os == 'ubuntu-latest'
        runs:
          using: composit
          env:
            MOBIFY_CLIENT_USER: ${{ secrets.MOBIFY_CLIENT_USER }}
            MOBIFY_CLIENT_API_KEY: ${{ secrets.MOBIFY_CLIENT_API_KEY }}
          steps:
            - name: Create MRT credentials file
              run: |-
                # Add credentials file at ~/.mobify so we can upload to Mobify Cloud
                npm run save-credentials --prefix packages/template-retail-react-app -- --user "$MOBIFY_CLIENT_USER" --key "$MOBIFY_CLIENT_API_KEY"
              shell: bash

      - name: Push Bundle
        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6 && matrix.os == 'ubuntu-latest'
        #TODO: Change target test-env to staging
        run: |-
          if [[ $DEVELOP || $RELEASE ]]; then
            target=test-env
            target_commerce_sdk_react="commerce-sdk-react"
          elif [[ $RELEASE ]]; then
            target=production
          else
            target=""
          fi
          project="scaffold-pwa"
          if [[ $target ]]; then
            npm run push --prefix packages/template-retail-react-app -- -s $project --message "build ${{ github.run_id }} on ${{ github.ref }} (${{ github.sha }})" --target $target
          fi
          if [[ $target_commerce_sdk_react ]]; then
            npm run push --prefix packages/test-commerce-sdk-react -- -s $project --message "test-commerce-sdk-react build ${{ github.run_id }} on ${{ github.ref }} (${{ github.sha }})" --target $target_commerce_sdk_react
          fi
      

  generated:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        template: [test-project, retail-react-app-demo, express-minimal-test-project, typescript-minimal-test-project]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Setup Ubuntu Machine
        if: matrix.os == 'ubuntu-latest'
        uses: "./.github/actions/setup_ubuntu"

      - name: Setup Windows Machine
        if: matrix.os == 'windows-latest'
        uses: "./.github/actions/setup_windows"

      - name: Generate ${{ matrix.template }} project
        run: |-
          set GENERATOR_PRESET=${{ matrix.template }}
          node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir generated-${{ matrix.template }}
        env:
          GENERATOR_PRESET: ${{ matrix.template }}
        timeout-minutes: 5

      - name: Run tests
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/runtests"
        with:
          cwd: generated-${{ matrix.template }}

      - name: Smoke test scripts
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        uses: "./.github/actions/smoketestscripts"
        with:
          dir: generated-${{ matrix.template }}

      - name: Count Generated Project Dependencies
        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
        run: |-
          MAX_PACKAGES="2250"
          total=$(./scripts/count-dependencies.js generated-${{ matrix.template }})
          echo "TOTAL_PACKAGES=${total}" >> $GITHUB_ENV

          if [ "$total" -gt "$MAX_PACKAGES" ]; then
              echo "Error: Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
              exit 1;
          else
              echo "Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
          fi
        shell: bash

      - name: Store Verdaccio logfile artifact
        uses: actions/upload-artifact@v3
        with:
          path: packages/pwa-kit-create-app/local-npm-repo/verdaccio.log
